### ISSUE TITLE
Cannot find module 'core-js/modules/web.dom.iterable

### ISSUE THREAD

**Issue by nicpitsch** [libeanim/inkdrop-open-in-external-editor#1]
**Error**

Latest Inkdrop version 4.5.0 raises this error on start-up:

```
app:error Error: Cannot find module 'core-js/modules/web.dom.iterable'
Require stack:
- C:\Users\user1\AppData\Roaming\inkdrop\packages\open-in-external-editor\lib\open-in-editor-message-dialog.js
- C:\Users\user1\AppData\Roaming\inkdrop\packages\open-in-external-editor\lib\open-in-editor.js
- D:\programs\Inkdrop\program\resources\app.asar\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (D:\programs\Inkdrop\program\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\user1\AppData\Roaming\inkdrop\packages\open-in-external-editor\lib\open-in-editor-message-dialog.js:4:1)
    at Object.<anonymous> (C:\Users\user1\AppData\Roaming\inkdrop\packages\open-in-external-editor\lib\open-in-editor-message-dialog.js:154:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.value [as .js] (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:4:10137)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (open-in-editor.js:3:1)
    at Object.<anonymous> (C:\Users\user1\AppData\Roaming\inkdrop\packages\open-in-external-editor\lib\open-in-editor.js:41:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.value [as .js] (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:4:10137)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at e.exports.requireMainModule (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:1:118796)
    at file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:1:105296
    at e.exports.measure (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:1:104139)
    at e.exports.load (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:1:104869)
    at e.exports.loadPackage (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:4:318906)
    at e.exports.loadPackages (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:4:317685)
    at V.start (file:///D:/programs/Inkdrop/program/resources/app.asar/browser-main.js:4:29843)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) +1ms
```

**Environment**

Inkdrop 4.5.0, Desktop, portable (zip), Windows 10.

Thanks for that useful plugin!

**Comment by libeanim** [comment]
@nicpitsch Thx for reporting, it should be fixed in version 0.1.4 of this plugin.

Run `ipm update` to get the newest version.
